"""updated receipt model 3

Revision ID: 0e72c69da55a
Revises: b6a722535b95
Create Date: 2025-11-12 21:36:55.203691

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e72c69da55a'
down_revision: Union[str, Sequence[str], None] = 'b6a722535b95'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("merchants", sa.Column("notes", sa.Text(), nullable=True))
    op.add_column('category', sa.Column('color', sa.String(length=7), nullable=False, server_default="#808080"))
    op.add_column('receipts', sa.Column('purchase_date', sa.Date(), nullable=False))
    op.add_column('receipts', sa.Column('receipt_photo', sa.String(length=500), nullable=True))
    op.add_column('product_list', sa.Column('product_photo', sa.String(length=500), nullable=True))
    op.drop_index(op.f('ix_receipts_date'), table_name='receipts')
    op.create_index(op.f('ix_receipts_purchase_date'), 'receipts', ['purchase_date'], unique=False)
    op.drop_column('receipts', 'date')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('receipts', sa.Column('date', sa.DATE(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_receipts_purchase_date'), table_name='receipts')
    op.create_index(op.f('ix_receipts_date'), 'receipts', ['date'], unique=False)
    op.drop_column('receipts', 'purchase_date')
    # ### end Alembic commands ###
