"""updated receipt model 2

Revision ID: 2a632b88c2af
Revises: 3bdf2729a979
Create Date: 2025-11-12 19:26:13.162428

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a632b88c2af'
down_revision: Union[str, Sequence[str], None] = '3bdf2729a979'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_category_name_unique', 'category', ['name'], unique=True)
    op.create_index(op.f('ix_category_id'), 'category', ['id'], unique=False)
    op.create_index(op.f('ix_category_name'), 'category', ['name'], unique=True)
    op.create_table('measurement_unit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('abbreviation', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_measurement_unit_abbreviation_unique', 'measurement_unit', ['abbreviation'], unique=True)
    op.create_index('idx_measurement_unit_name_unique', 'measurement_unit', ['name'], unique=True)
    op.create_index(op.f('ix_measurement_unit_abbreviation'), 'measurement_unit', ['abbreviation'], unique=True)
    op.create_index(op.f('ix_measurement_unit_id'), 'measurement_unit', ['id'], unique=False)
    op.create_index(op.f('ix_measurement_unit_name'), 'measurement_unit', ['name'], unique=True)
    op.create_table('merchants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_merchants_id'), 'merchants', ['id'], unique=False)
    op.create_index(op.f('ix_merchants_name'), 'merchants', ['name'], unique=True)
    op.create_table('product_list',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('barcode', sa.String(length=50), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('measurement_unit_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['measurement_unit_id'], ['measurement_unit.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_product_list_barcode_unique', 'product_list', ['barcode'], unique=True, postgresql_where=sa.text('barcode IS NOT NULL'))
    op.create_index('idx_product_list_name_unique', 'product_list', ['name'], unique=True)
    op.create_index(op.f('ix_product_list_barcode'), 'product_list', ['barcode'], unique=True)
    op.create_index(op.f('ix_product_list_category_id'), 'product_list', ['category_id'], unique=False)
    op.create_index(op.f('ix_product_list_id'), 'product_list', ['id'], unique=False)
    op.create_index(op.f('ix_product_list_measurement_unit_id'), 'product_list', ['measurement_unit_id'], unique=False)
    op.create_index(op.f('ix_product_list_name'), 'product_list', ['name'], unique=True)
    op.create_table('product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('price', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('description', sa.String(length=100), nullable=True),
    sa.Column('receipt_id', sa.Integer(), nullable=False),
    sa.Column('product_list_id', sa.Integer(), nullable=False),
    sa.CheckConstraint('price >= 0', name='constraint_check_product_price_negative'),
    sa.CheckConstraint('quantity > 0', name='constraint_check_product_quantity_zero'),
    sa.ForeignKeyConstraint(['product_list_id'], ['product_list.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['receipt_id'], ['receipts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_id'), 'product', ['id'], unique=False)
    op.create_index(op.f('ix_product_product_list_id'), 'product', ['product_list_id'], unique=False)
    op.create_index(op.f('ix_product_receipt_id'), 'product', ['receipt_id'], unique=False)
    op.add_column('receipts', sa.Column('merchant_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'receipts', 'merchants', ['merchant_id'], ['id'], ondelete='RESTRICT')
    op.drop_column('receipts', 'total_price')
    op.drop_column('receipts', 'notes')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('receipts', sa.Column('notes', sa.VARCHAR(length=80), autoincrement=False, nullable=True))
    op.add_column('receipts', sa.Column('total_price', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'receipts', type_='foreignkey')
    op.drop_column('receipts', 'merchant_id')
    op.drop_index(op.f('ix_product_receipt_id'), table_name='product')
    op.drop_index(op.f('ix_product_product_list_id'), table_name='product')
    op.drop_index(op.f('ix_product_id'), table_name='product')
    op.drop_table('product')
    op.drop_index(op.f('ix_product_list_name'), table_name='product_list')
    op.drop_index(op.f('ix_product_list_measurement_unit_id'), table_name='product_list')
    op.drop_index(op.f('ix_product_list_id'), table_name='product_list')
    op.drop_index(op.f('ix_product_list_category_id'), table_name='product_list')
    op.drop_index(op.f('ix_product_list_barcode'), table_name='product_list')
    op.drop_index('idx_product_list_name_unique', table_name='product_list')
    op.drop_index('idx_product_list_barcode_unique', table_name='product_list', postgresql_where=sa.text('barcode IS NOT NULL'))
    op.drop_table('product_list')
    op.drop_index(op.f('ix_merchants_name'), table_name='merchants')
    op.drop_index(op.f('ix_merchants_id'), table_name='merchants')
    op.drop_table('merchants')
    op.drop_index(op.f('ix_measurement_unit_name'), table_name='measurement_unit')
    op.drop_index(op.f('ix_measurement_unit_id'), table_name='measurement_unit')
    op.drop_index(op.f('ix_measurement_unit_abbreviation'), table_name='measurement_unit')
    op.drop_index('idx_measurement_unit_name_unique', table_name='measurement_unit')
    op.drop_index('idx_measurement_unit_abbreviation_unique', table_name='measurement_unit')
    op.drop_table('measurement_unit')
    op.drop_index(op.f('ix_category_name'), table_name='category')
    op.drop_index(op.f('ix_category_id'), table_name='category')
    op.drop_index('idx_category_name_unique', table_name='category')
    op.drop_table('category')
    # ### end Alembic commands ###
