"""updated receipt model

Revision ID: 3bdf2729a979
Revises: fb54a631a0dc
Create Date: 2025-11-06 23:55:50.099756

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3bdf2729a979'
down_revision: Union[str, Sequence[str], None] = 'fb54a631a0dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('receipts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('total_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('barcode', sa.String(length=20), nullable=True),
    sa.Column('notes', sa.String(length=80), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('total_price >= 0', name='constraint_check_negative_receipt'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_receipts_date'), 'receipts', ['date'], unique=False)
    op.create_index(op.f('ix_receipts_id'), 'receipts', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_receipts_id'), table_name='receipts')
    op.drop_index(op.f('ix_receipts_date'), table_name='receipts')
    op.drop_table('receipts')
    # ### end Alembic commands ###
